name = "yolo_test"

[distance]
biden = {horizontal = 28.6, vertical = 15.9}
shiny = {horizontal = 28.6, vertical = 16.1}
Skywalker = {horizontal = 24, vertical = 16}
Elon = {horizontal = 28, vertical = 16}


[detect]
model_path = "models/2023-08-25_fly-detection.onnx"
data_path = "outputs/2023-08-09_biden"
minimum_confidence = 0.01
parquet = "False"
csv_path = "outputs/2023-08-09_biden/csv"

#output_path = ""


# Model Training Configuration
# ----------------------------
# Ignore these unless you're trying to train a fly detection model.
[assemble]
data_dir = "data/"
datasets = [
    "2023-07-12_biden"
  , "2023-07-19_biden"
  , "2023-07-19_shiny"
  , "2023-07-22_shiny"
  , "2023-07-26_shiny"
  , "2023-08-09_biden"
]
test_size = 0.2
seed = 1931
#out_dir = "outputs/training"

[train]
pretrain_path = "models/yolov8x.pt"
data_path = "outputs/yolo_test/yolo_test.yaml"
epochs = 10
patience = 20
