# Model Training Configuration
# ----------------------------
# Ignore these unless you're trying to train a fly detection model.
name = "yolo_test"

[assemble]
data_dir = "data/"
datasets = [
    "2023-07-12_biden"
  , "2023-07-19_biden"
  , "2023-07-19_shiny"
  , "2023-07-22_shiny"
  , "2023-07-26_shiny"
  , "2023-08-09_biden"
]
test_size = 0.2
seed = 1931
#out_dir = "outputs/training"

[train]
pretrain_path = "models/yolov8x.pt"
data_path = "outputs/yolo_test/yolo_test.yaml"
epochs = 10
patience = 20
